# Generated by Django 2.2 on 2020-04-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='aftermath',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='times_voted',
            field=models.IntegerField(default=0),
        ),
    ]
