# Generated by Django 2.2 on 2020-04-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200421_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
