# Generated by Django 2.2 on 2020-04-27 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20200427_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='forum.Thread')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poll_choices', to='forum.Poll')),
            ],
        ),
    ]
